### ISSUE TITLE
Expo Error: null is not an object

### ISSUE THREAD

**Issue by theobouwman** [mwegener-com/with-rn-image-crop-picker#2]
I get this issue:
```
TypeError: null is not an object (evaluating 'ImageCropPicker.openPicker')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

I installed:
```
    "react-native-image-crop-picker": "^0.36.4",
    "with-rn-image-crop-picker": "^0.2.0"
```
And use this code:
```
import ImagePicker from 'react-native-image-crop-picker';
 ImagePicker.openPicker({
            width: 300,
            height: 400,
            cropping: true
        }).then(image => {
            console.log(image);
        });
```

**Comment by Abdelnacerr** [comment]
I am using expo dev client and getting the same errors, any fixes yet?

**Comment by mwegener-com** [comment]
@Abdelnacerr Did you follow all these steps under "usage" in Readme?
